### ISSUE TITLE
Add support for minecraft schematics loading

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg-dapp#31]
We need a way to add nature on the terrain generation, I don't have much lead on this because everything needs collision but maybe we could use minecraft's schematics files like those https://www.planetminecraft.com/project/luna-s-custom-spruce-trees/ and transform it to our custom voxel format ? those trees are just made of blocks so it might be easier to use

**Comment by etienne-85** [comment]
- [x] biome initial implementation for  default (`temperate`), `desert`, `artic` 
- [ ] smooth transition between biomes
- [ ] tweak biome conf to improve existing biomes and add support to other types like `tropical`...
- [ ] extends biome conf to support more customization parameters like vegetation type spawn, ...

**Comment by Sceat** [comment]
https://github.com/PrismarineJS/prismarine-schematic
